function FFproc_plotmatrix(app,FC,tf,tw)
    
    global font 
    
    if ~app.all.State
        ncm = cat(1,FC{tf}(1:end).NCM); 
        ncm(ncm == 0) = complex(NaN,NaN);
        sdm = cat(1,FC{tf}(1:end).SDM);
        sdmrob = cat(1,FC{tf}(1:end).SDM_rob);
    else
        ncm = cat(1,FC{tf}(tw).NCM);    
        ncm(ncm == 0) = complex(NaN,NaN);
        sdm = cat(1,FC{tf}(tw).SDM);
        sdmrob = cat(1,FC{tf}(tw).SDM_rob);
    end
    
    for i = 1:size(ncm,2)
        for j = 1:size(ncm,2)
            for k = i:size(ncm,2):size(ncm,1)
                ncm_mean(k,1) = ncm(k,j);
                sdm_mean(k,1) = sdm(k,j);
                sdmrob_mean(k,1) = sdmrob(k,j);
            end
            ncm_mean = ncm_mean(ncm_mean~=0);
            ncm_mean = ncm_mean(~isnan(ncm_mean));
            sdm_mean = sdm_mean(sdm_mean~=0);
            sdm_mean = sdm_mean(~isnan(sdm_mean));
            sdmrob_mean = sdmrob_mean(sdmrob_mean~=0);
            sdmrob_mean = sdmrob_mean(~isnan(sdmrob_mean));
            NCM(i,j) = complex(median(real(ncm_mean)),median(imag(ncm_mean)));
            SDM(i,j) = complex(median(real(sdm_mean)),median(imag(sdm_mean)));
            SDM_Rob(i,j) = complex(median(real(sdmrob_mean)),median(imag(sdmrob_mean)));
            clear ncm_mean sdm_mean sdmrob_mean
        end
    end
    
    NCM(isnan(real(NCM))) = complex(NaN,NaN);
    
    NCM_r = real(NCM);              NCM_i = imag(NCM);
    NCM_r(NCM_r<1) = 1;             NCM_i(NCM_i<1) = 1;
    SDM_r = real(SDM);              SDM_i = imag(SDM);
    SDM_r(SDM_r<1) = 1;             SDM_i(SDM_i<1) = 1;
    SDM_Rob_r = real(SDM_Rob);      SDM_Rob_i = imag(SDM_Rob);
    SDM_Rob_r(SDM_Rob_r<1) = 1;     SDM_Rob_i(SDM_Rob_i<1) = 1;
    
    for i = 1:size(NCM,2)/5
        chan{1,i} = ['Ex_',num2str(i)];
        chan{2,i} = ['Ey_',num2str(i)];
        chan{3,i} = ['Bx_',num2str(i)];
        chan{4,i} = ['By_',num2str(i)];
        chan{5,i} = ['Bz_',num2str(i)];
    end
    
    ax = subplot(2,3,1,'Parent',app.MATPanel);  
    cla(ax','reset')
    m = imagesc(ax,NCM_r);
    m.AlphaData = double(~isnan(m.CData));
    set(ax,'Fontname',font,'Fontsize',10,...
           'box','on',...
           'XLim',[0.5,numel(chan)+0.5],...
           'YLim',[0.5,numel(chan)+0.5],...
           'XTick',1:numel(chan(:)),...
           'YTick',1:numel(chan(:)),...
           'XTickLabels',chan(:),...         
           'YTickLabels',chan(:),...
           'XAxisLocation','Top',...
           'YDir','reverse',...
           'MinorGridLineStyle','none',...
           'ColorScale','log'); 
    caxis(ax,[10^ceil(log10(min(NCM_r(:)))),10^floor(log10(max(NCM_r(:))))])
    colormap(ax,colors('viridis'))
%     colormap(ax,flipud(colors('pastel',31)))
    cb = colorbar(ax);
    cb.Label.String = '(mV/Km)^2 or (nT)^2';
    title(ax,'NCM')       
           
    ax = subplot(2,3,2,'Parent',app.MATPanel);  
    cla(ax','reset') 
    imagesc(ax,SDM_r)
    set(ax,'Fontname',font,'Fontsize',10,...
           'box','on',...
           'layer','top',...
           'XLim',[0.5,numel(chan)+0.5],...
           'YLim',[0.5,numel(chan)+0.5],...
           'XTick',1:numel(chan(:)),...
           'YTick',1:numel(chan(:)),...
           'XTickLabels',chan(:),...         
           'YTickLabels',chan(:),...
           'XAxisLocation','Top',...
           'YDir','reverse',...
           'MinorGridLineStyle','none',...
           'ColorScale','log'); 
    caxis(ax,[10^ceil(log10(min(SDM_r(:)))),10^floor(log10(max(SDM_r(:))))])
    colormap(ax,colors('viridis'))
%     colormap(ax,flipud(colors('pastel',31)))
    cb = colorbar(ax);
    cb.Label.String = '(mV/Km)^2 or (nT)^2';
    title(ax,'\Re SDM')
    
    ax = subplot(2,3,3,'Parent',app.MATPanel);  
    cla(ax','reset')  
    imagesc(ax,SDM_i)
    set(ax,'Fontname',font,'Fontsize',10,...
           'box','on',...
           'layer','top',...
           'XLim',[0.5,numel(chan)+0.5],...
           'YLim',[0.5,numel(chan)+0.5],...
           'XTick',1:numel(chan(:)),...
           'YTick',1:numel(chan(:)),...
           'XTickLabels',chan(:),...         
           'YTickLabels',chan(:),...
           'XAxisLocation','Top',...
           'YDir','reverse',...
           'MinorGridLineStyle','none',...
           'ColorScale','log'); 
    caxis(ax,[10^ceil(log10(min(SDM_i(:)))),10^floor(log10(max(SDM_i(:))))])
    colormap(ax,colors('viridis'))
%     colormap(ax,flipud(colors('pastel',31)))
    cb = colorbar(ax);
    cb.Label.String = '(mV/Km)^2 or (nT)^2';
    title(ax,'\Im SDM')
    
    ax = subplot(2,3,5,'Parent',app.MATPanel);  
    cla(ax','reset')  
    imagesc(ax,SDM_Rob_r)
    set(ax,'Fontname',font,'Fontsize',10,...
           'box','on',...
           'layer','top',...
           'XLim',[0.5,numel(chan)+0.5],...
           'YLim',[0.5,numel(chan)+0.5],...
           'XTick',1:numel(chan(:)),...
           'YTick',1:numel(chan(:)),...
           'XTickLabels',chan(:),...         
           'YTickLabels',chan(:),...
           'XAxisLocation','Top',...
           'YDir','reverse',...
           'MinorGridLineStyle','none',...
           'ColorScale','log'); 
    caxis(ax,[10^ceil(log10(min(SDM_Rob_r(:)))),10^ceil(log10(max(SDM_Rob_r(:))))])
    colormap(ax,colors('viridis'))
%     colormap(ax,flipud(colors('pastel',31)))
    cb = colorbar(ax);
    cb.Label.String = '(mV/Km)^2 or (nT)^2';
    title(ax,'\Re SDM Robust-Scaled')
    
    ax = subplot(2,3,6,'Parent',app.MATPanel);  
    cla(ax','reset')
 
    imagesc(ax,SDM_Rob_i)
    set(ax,'Fontname',font,'Fontsize',10,...
           'box','on',...
           'layer','top',...
           'XLim',[0.5,numel(chan)+0.5],...
           'YLim',[0.5,numel(chan)+0.5],...
           'XTick',1:numel(chan(:)),...
           'YTick',1:numel(chan(:)),...
           'XTickLabels',chan(:),...         
           'YTickLabels',chan(:),...
           'XAxisLocation','Top',...
           'YDir','reverse',...
           'MinorGridLineStyle','none',...
           'ColorScale','log'); 
    caxis(ax,[10^ceil(log10(min(SDM_Rob_i(:)))),10^ceil(log10(max(SDM_Rob_i(:))))])
    colormap(ax,colors('viridis'))
%     colormap(ax,flipud(colors('pastel',31)))
    cb = colorbar(ax);
    cb.Label.String = '(mV/Km)^2 or (nT)^2';
    title(ax,'\Im SDM Robust-Scaled')
    
end