function plot_rhophiRAW(app,info,ranking,RAW,targ)
    
    warning off
    load('rho1.mat')
    load('rho2.mat')
    
    n = numel(RAW(2).site);
    leg = cell(2,n);
    name = RAW(2).site;
    per = RAW(2).per;
    
    td = tiledlayout(2,2,'Parent',targ,'TileSpacing','compact','Padding','compact');

    % Resistivity
    ax = nexttile(td);
    cla(ax)
    hold(ax,'on')
    grid(ax,'on')
    
    for i = 1:n
        errorbar(ax,per,RAW(ranking).rhoxy(:,i),...
                    RAW(ranking).rhoxy_Err(:,i),'o','color',rho1(i,:),...
                    'MarkerSize',6,'MarkerEdgeColor',rho1(i,:),'MarkerFaceColor',rho1(i,:),...
                    'capsize',3)
        errorbar(ax,per,RAW(ranking).rhoyx(:,i),...
                    RAW(ranking).rhoyx_Err(:,i),'o','color',rho2(i,:),...
                    'MarkerSize',6,'MarkerEdgeColor',rho2(i,:),'MarkerFaceColor',rho2(i,:),...
                    'capsize',3)
        leg(1,i) = {[name{i},' \rhoxy']};
        leg(2,i) = {[name{i},' \rhoyx']};
    end
    
    xlim(ax,[floor(min(per)) ceil(max(per))])
    ylim(ax,[floor(min(min([cat(1,RAW.rhoxy);cat(1,RAW.rhoyx)])))...
             ceil(max(max([cat(1,RAW.rhoxy);cat(1,RAW.rhoyx)])))])
    xlabel(ax,'period (s)')  
    ylabel(ax,'App. Resistivity \rho_a (\Omegam)')

    set(ax,'Fontname','Verdana','Fontsize',12,...
           'box','on','Xscale','log','Yscale','log',...
           'xlim',10.^[info.permin info.permax],...
           'ylim',10.^[info.rhomin info.rhomax],...
           'xtick',10.^(ceil(info.permin):floor(info.permax)),...            
           'ytick',10.^(ceil(info.rhomin):floor(info.rhomax)),...
           'MinorGridLineStyle','none')
    
    L = legend(ax,'location','northeast','NumColumns',n,'Fontsize',8);
    L.String = leg;

    % TXZ
    ax = nexttile(td);
    cla(ax)
    hold(ax,'on')
    grid(ax,'on')
    
    for i = 1:n
        errorbar(ax,per,real(RAW(ranking).txz(:,i)),...
                    RAW(ranking).txz_Err(:,i),'o','color',rho1(i,:),...
                    'MarkerSize',6,'MarkerEdgeColor',rho1(i,:),'MarkerFaceColor',rho1(i,:),...
                    'capsize',3)
        errorbar(ax,per,imag(RAW(ranking).txz(:,i)),...
                    RAW(ranking).txz_Err(:,i),'o','color',rho2(i,:),...
                    'MarkerSize',6,'MarkerEdgeColor',rho2(i,:),'MarkerFaceColor',rho2(i,:),...
                    'capsize',3)
        leg(1,i) = {[name{i},' real']};
        leg(2,i) = {[name{i},' imag']};
    end
    
    xlim(ax,[floor(min(per)) ceil(max(per))])
    ylim(ax,[floor(min(min([real(cat(1,RAW.txz));imag(cat(1,RAW.txz))])))...
              ceil(max(max([real(cat(1,RAW.txz));imag(cat(1,RAW.txz))])))])
    xlabel(ax,'period (s)')  
    ylabel(ax,'TXZ')

    set(ax,'Fontname','Verdana','Fontsize',12,...
           'box','on','Xscale','log','Yscale','linear',...
           'xlim',10.^[info.permin info.permax],...
           'ylim',[-info.txz info.txz],...
           'xtick',10.^(ceil(info.permin):floor(info.permax)),...            
           'MinorGridLineStyle','none')
    
    L = legend(ax,'location','northeast','NumColumns',n,'Fontsize',8);
    L.String = leg;
    
    % Phase
    ax = nexttile(td);
    cla(ax)
    hold(ax,'on')
    grid(ax,'on')
    clear leg
    
    for i = 1:n
        errorbar(ax,per,RAW(ranking).phixy(:,i),...
                    RAW(ranking).phixy_Err(:,i),'o','color',rho1(i,:),...
                    'MarkerSize',6,'MarkerEdgeColor',rho1(i,:),'MarkerFaceColor',rho1(i,:),...
                    'capsize',3)
        errorbar(ax,per,RAW(ranking).phiyx(:,i) + 180,...
                    RAW(ranking).phiyx_Err(:,i),'o','color',rho2(i,:),...
                    'MarkerSize',6,'MarkerEdgeColor',rho2(i,:),'MarkerFaceColor',rho2(i,:),...
                    'capsize',3)
        leg(1,i) = {[name{i},' \phixy']};
        leg(2,i) = {[name{i},' \phiyx']};
    end
    
    xlim(ax,[floor(min(per)) ceil(max(per))])
    ylim(ax,[0 90])
    xlabel(ax,'period (s)')  
    ylabel(ax,'Phase (deg)')

    set(ax,'Fontname','Verdana','Fontsize',12,...
           'box','on','Xscale','log','Yscale','linear',...
           'xlim',10.^[info.permin info.permax],...
           'ylim',[info.phimin info.phimax],...
           'xtick',10.^(ceil(info.permin):floor(info.permax)),...            
           'ytick',sort([info.phimin:30:info.phimax,45]),...
           'MinorGridLineStyle','none')
    
    L = legend(ax,'location','northeast','NumColumns',n,'Fontsize',8);
    L.String = leg;

    % TYZ
    ax = nexttile(td);
    cla(ax)
    hold(ax,'on')
    grid(ax,'on')
    
    for i = 1:n
        errorbar(ax,per,real(RAW(ranking).tyz(:,i)),...
                    RAW(ranking).tyz_Err(:,i),'o','color',rho1(i,:),...
                    'MarkerSize',6,'MarkerEdgeColor',rho1(i,:),'MarkerFaceColor',rho1(i,:),...
                    'capsize',3)
        errorbar(ax,per,imag(RAW(ranking).tyz(:,i)),...
                    RAW(ranking).tyz_Err(:,i),'o','color',rho2(i,:),...
                    'MarkerSize',6,'MarkerEdgeColor',rho2(i,:),'MarkerFaceColor',rho2(i,:),...
                    'capsize',3)
        leg(1,i) = {[name{i},' real']};
        leg(2,i) = {[name{i},' imag']};
    end
    
    xlim(ax,[floor(min(per)) ceil(max(per))])
    ylim(ax,[floor(min(min([real(cat(1,RAW.tyz));imag(cat(1,RAW.tyz))])))...
              ceil(max(max([real(cat(1,RAW.tyz));imag(cat(1,RAW.tyz))])))])
    xlabel(ax,'period (s)')  
    ylabel(ax,'TXZ')

    set(ax,'Fontname','Verdana','Fontsize',12,...
           'box','on','Xscale','log','Yscale','linear',...
           'xlim',10.^[info.permin info.permax],...
           'ylim',[-info.tyz info.tyz],...
           'xtick',10.^(ceil(info.permin):floor(info.permax)),...            
           'MinorGridLineStyle','none')
    
    L = legend(ax,'location','northeast','NumColumns',n,'Fontsize',8);
    L.String = leg;

    title(td,['Estimations for the best-ranked ',num2str(ranking),'% time segments'],'Fontname','Verdana','Fontsize',16)
    
end